blueprint:
  name: GoodWe & Tibber Smart Charge (Optimiert)
  description: |
    **Intelligente Batteriesteuerung für GoodWe Wechselrichter mit Tibber**
    
    Dieses Blueprint optimiert deinen Speicher vollautomatisch, um Stromkosten zu senken und den Eigenverbrauch zu maximieren.

    **Funktionsweise:**
    1. **Günstiges Laden:** Der Akku wird in den **X günstigsten Stunden** des Tages (basierend auf Tibber-Preisen für heute & morgen) aus dem Netz geladen (Modus: Backup).
    2. **Intelligente Zurückhaltung:** Wenn für die günstigen Stunden genug **Solarstrom vorhergesagt** ist (über optionalen Forecast-Sensor) oder aktuell die Sonne scheint, wird das Netzladen übersprungen, um kostenlosen Solarstrom zu nutzen.
    3. **Export-Management:** Im Eigenverbrauchsmodus (General) wird die **Exportsperre** automatisch aktiviert, wenn der Akku entladen wird (um Netzbezug/Verluste zu minimieren), und deaktiviert, wenn der Akku voll ist (um Überschuss einzuspeisen).

    **Voraussetzungen:**
    * **HACS GoodWe Integration:** Für die Steuerung von Modus & Exportsperre.
    * **Tibber Daten-Sensor:** Ein manuell angelegter Template/REST-Sensor, der die Attribute `today` und `tomorrow` liefert (siehe Anleitung im Blog).
    * **(Optional) Solar Forecast:** Ein Sensor von `ha-solar-forecast-ml` o.ä. für noch präzisere Entscheidungen.

  domain: automation
  input:
    tibber_price_data_sensor:
      name: Tibber Preisdaten Sensor
      description: >
        Der Sensor, der die stündlichen Preise als Attribute 'today' und 'tomorrow' enthält.
        (Meistens ein manuell erstellter REST-Sensor in der configuration.yaml).
      selector:
        entity:
          domain: sensor
    pv_power_sensor:
      name: Aktuelle PV-Leistung (W)
      description: Sensor für die aktuelle Erzeugung des Wechselrichters (z.B. sensor.goodwe_pv_power).
      selector:
        entity:
          domain: sensor
          device_class: power
    battery_soc_sensor:
      name: Batterie Ladestand (%)
      description: Sensor für den aktuellen SOC der Batterie (z.B. sensor.goodwe_battery_soc).
      selector:
        entity:
          domain: sensor
          device_class: battery
    goodwe_work_mode_selector:
      name: GoodWe Betriebsmodus Selector
      description: >
        Die Entität zum Umschalten des Modus (z.B. select.goodwe_work_mode). 
        Muss Optionen wie 'General' und 'Backup' haben.
      selector:
        entity:
          domain: select
    goodwe_export_limit_switch:
      name: GoodWe Exportsperre Schalter
      description: >
        Der Schalter zum Ein-/Ausschalten der Einspeisebegrenzung (z.B. switch.goodwe_export_limit).
      selector:
        entity:
          domain: switch
    solar_forecast_sensor:
      name: Solar Prognose Sensor (Optional)
      description: >
        Ein Sensor, der die erwartete Solarleistung in Watt liefert. 
        Wenn nicht vorhanden, wird nur die aktuelle PV-Leistung berücksichtigt.
      default: null
      selector:
        entity:
          domain: sensor
    charge_hours:
      name: Ladedauer Stunden
      description: >
        Anzahl der günstigsten Stunden, in denen geladen werden soll.
        Faustformel: Batteriekapazität (kWh) / Ladeleistung (kW) = Stunden (aufgerundet).
      default: 3
      selector:
        number:
          min: 1
          max: 8
          unit_of_measurement: "Stunden"
    pv_threshold_low:
      name: PV-Schwellenwert Niedrig (W)
      description: >
        Unterhalb dieses Wertes gilt: "Keine nennenswerte Sonne".
        Wird genutzt, um Netzladen zu erlauben oder Exportsperre zu aktivieren.
      default: 50
      selector:
        number:
          min: 0
          unit_of_measurement: "W"
    pv_threshold_high:
      name: PV
